### ISSUE TITLE
Contribution to the teamcity git-plugin

### ISSUE THREAD

**Issue by ilucker** [nd/for.tests#13]
Hello. I'm sorry if this is a wrong place to write. I want to make a contribution to the teamcity git-plugin but can't find a proper place to do this. 
I've created 2 PRs. Could you please review them and let me know what do you think   
- https://github.com/ilucker/teamcity-git-plugin/pull/1
- https://github.com/ilucker/teamcity-git-plugin/pull/2

Thank you.

**Comment by nd** [comment]
Hi Alexander,

could you please create issues in youtrack.jetbrains.com describing what
problem you have with current plugin behavior?
